// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/commentcov.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentcovPluginClient is the client API for CommentcovPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentcovPluginClient interface {
	MeasureCoverage(ctx context.Context, in *MeasureCoverageIn, opts ...grpc.CallOption) (*MeasureCoverageOut, error)
}

type commentcovPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentcovPluginClient(cc grpc.ClientConnInterface) CommentcovPluginClient {
	return &commentcovPluginClient{cc}
}

func (c *commentcovPluginClient) MeasureCoverage(ctx context.Context, in *MeasureCoverageIn, opts ...grpc.CallOption) (*MeasureCoverageOut, error) {
	out := new(MeasureCoverageOut)
	err := c.cc.Invoke(ctx, "/proto.CommentcovPlugin/MeasureCoverage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentcovPluginServer is the server API for CommentcovPlugin service.
// All implementations must embed UnimplementedCommentcovPluginServer
// for forward compatibility
type CommentcovPluginServer interface {
	MeasureCoverage(context.Context, *MeasureCoverageIn) (*MeasureCoverageOut, error)
	mustEmbedUnimplementedCommentcovPluginServer()
}

// UnimplementedCommentcovPluginServer must be embedded to have forward compatible implementations.
type UnimplementedCommentcovPluginServer struct {
}

func (UnimplementedCommentcovPluginServer) MeasureCoverage(context.Context, *MeasureCoverageIn) (*MeasureCoverageOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MeasureCoverage not implemented")
}
func (UnimplementedCommentcovPluginServer) mustEmbedUnimplementedCommentcovPluginServer() {}

// UnsafeCommentcovPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentcovPluginServer will
// result in compilation errors.
type UnsafeCommentcovPluginServer interface {
	mustEmbedUnimplementedCommentcovPluginServer()
}

func RegisterCommentcovPluginServer(s grpc.ServiceRegistrar, srv CommentcovPluginServer) {
	s.RegisterService(&CommentcovPlugin_ServiceDesc, srv)
}

func _CommentcovPlugin_MeasureCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureCoverageIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentcovPluginServer).MeasureCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommentcovPlugin/MeasureCoverage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentcovPluginServer).MeasureCoverage(ctx, req.(*MeasureCoverageIn))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentcovPlugin_ServiceDesc is the grpc.ServiceDesc for CommentcovPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentcovPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CommentcovPlugin",
	HandlerType: (*CommentcovPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MeasureCoverage",
			Handler:    _CommentcovPlugin_MeasureCoverage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/commentcov.proto",
}
